typography_spectrum: 0.23268655012361705
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.34160178899765015
  lightness: 0.08517080126330256
  saturation: 0.5161915207281709
  rhythmicContrast: 0.921463972190395
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.73624
analytics:
  google: UA-46059547-1
  facebook: null
  twitter: null
author:
  url: 'http://augmentl.io'
  name: Augmentl
  email: write@augmentl.io
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7a1bbe8e-ef4f-4c29-afdb-4cf9a08647c4.jpg
name: ɅUGMΞNTL.IO
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
navigation:
  - name: About
    id: 224b47f6-c7e5-49c1-a745-b7217c466694
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ɅUGMΞNTL
description: News and Views on Virtual Reality
purpose: []
