name: Augmentl
favicon: null
layout_spectrum: 0.46515
typography_spectrum: 0.79763
title: Augmentl
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46059547-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bfbfbf'
    - '#ff6666'
    - '#990000'
  brandStrength: 0.1875
  lightness: 0.546595
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
