name: Augmentl
favicon: null
layout_spectrum: 0.43643
typography_spectrum: 0.81176
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ɅUGMΞNTL
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46059547-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afafaf'
    - '#ff9400'
    - '#ffffff'
    - '#323232'
    - '#d2d2d2'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
