name: Augmentl
favicon: null
layout_spectrum: 0.46515
typography_spectrum: 0.79763
title: Augmentl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46059547-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bfbfbf'
    - '#ff6666'
    - '#990000'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
