name: Augmentl
favicon: null
layout_spectrum: 0.46515
typography_spectrum: 0.6603
title: 'Augmentl: remixing reality'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bfbfbf'
    - '#ff6666'
    - '#990000'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
