name: Augmentl
favicon: null
layout_spectrum: 0.44762
typography_spectrum: 0.6603
title: 'Augmentl: the Mixed Reality Website'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171717'
    - '#705965'
    - '#9c9cbd'
    - '#937592'
    - '#d7ddcc'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
