name: ɅUGMΞNTL.IO
favicon: null
layout_spectrum: 0.73624
typography_spectrum: 0.37706
title: ɅUGMΞNTL
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
style: the-composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46059547-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afafaf'
    - '#ff9400'
    - '#ffffff'
    - '#323232'
    - '#d2d2d2'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
