name: Augmentl
favicon: null
layout_spectrum: 0.46515
typography_spectrum: 0.6603
title: 'Augmentl: remixing reality'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#a3c7d7'
    - '#0f1922'
    - '#74a3b7'
    - '#37454e'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
